### ISSUE TITLE
BUG: docker container fails due to internal pathing issues

### ISSUE THREAD

**Issue by artis3n** [bobheadxi/readable#21]
Just following the README instructions with the `latest` tag:

![image](https://user-images.githubusercontent.com/6969296/236572922-75d3e3c1-bb40-4516-8b65-2ac05ce4e6e7.png)

Trying the latest release has a different failure:

![image](https://user-images.githubusercontent.com/6969296/236573015-0e2071a7-dbe8-4afb-91b4-527dd15b466d.png)

The `v0.2.2` image works

**Comment by rooterkyberian** [comment]
Same with deno:
```
$ deno install --allow-read --allow-write https://deno.land/x/readable/readable.ts
Download ⠦ https://deno.land/x/readable/readable.ts                                                     Warning Implicitly using latest version (v0.3.0) for https://deno.land/x/readable/readable.ts
error: Relative import path "log/mod.ts" not prefixed with / or ./ or ../
    at https://deno.land/x/readable@v0.3.0/cmd/check.ts:1:24
```

**Comment by SilasK** [comment]
I have still the same issue with deno 

```
% deno install --allow-read --allow-write https://deno.land/x/readable/readable.ts
error: Relative import path "log/mod.ts" not prefixed with / or ./ or ../
    at https://deno.land/x/readable@v0.5.0/readable.ts:3:27
```

on macos 
Warning Implicitly using latest version (v0.5.0) for https://deno.land/x/readable/readable.ts

**Comment by SilasK** [comment]
I got it to work, by cloning the repo and using the mapping. is there a way to do this from the remote repo?
